### ISSUE TITLE
*Enhancement* generate crash logs

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#16]
I was wondering if it would be possible to have the engine generate crash logs every time the game crashes. This because some events, like GNN reports, appear to be randomly generated, and cannot always be reproduced by saving/loading, and they seem to be behind most of the current crashes.

**Comment by KilgoreTroutMaskReplicant** [comment]
Crash logs would be nice but not really feasible to implement. To get crash logs I run 1oom via valgrind or gdb.

To reproduce the randomly appearing GNN reports I just hack the code to always show the news (the saves are still important here to provide the content). As for general reproducibility... if the stars would not blink, the game would be fully deterministic. (Ground battle click-to-finish also affects the RNG but does not have the same ring to it.) The same sequence of numbers would be given every time for a given (save) game. I could make the star blinking use its own RNG seed, but am not sure if it is a wise choice.

...anyway. Crash logs? Sorry, not feasible.
