### ISSUE TITLE
Plague on Orion

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#17]
Running git commit 9effc9d

Issue: Orion was apparently contaminated by a plague even though it is not yet colonized at this stage of the game

How to reproduce:

1 - Load save 8 "undo" and skip turn

[orion plague.zip](https://github.com/KilgoreTroutMaskReplicant/1oom/files/1987951/orion.plague.zip)

![orion plague](https://user-images.githubusercontent.com/3621746/39816876-d6da22ac-539c-11e8-9c15-d9bb242c8c1c.png)

**Comment by KilgoreTroutMaskReplicant** [comment]
The save has a plague in Ursa. This is actually a report on piracy on Orion (which can happen in MOO1) but suffering of bug #14. This was fixed by commit d550e49d05cc1ff9bb4b9f032a88644c5ac26c6f which fixed that bug.
