### ISSUE TITLE
Compiling enforces 300x200 resolution by default

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#2]
I would suggest a higher resolution to be enabled by default when compiliing (possibly 600x400).

**Comment by KilgoreTroutMaskReplicant** [comment]
There may be two conflated issues here:
1. The default window size is 320x200. Workaround: resize your window, start with -winw 640 -winh 400 or press Alt-Enter to go fullscreen.
2. If OpenGL was not found during configure (see config.log) then 320x200 is the only size.

I will make the default window size (if OpenGL is available) be a bit more reasonable. Case 2 will stay as is; see HACKING and get the required OpenGL headers.

**Comment by sheepo99** [comment]
I've been using the resize windows cmds you suggested. I was just thinking it would be fine to have it default on 640x400 right after compiling.
