### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#4]
Crash after end of turn. I suppose because of another diplomatic message?

Running latest downloaded copy of master branch compiled today.

How to replicate crash:

1 - Load save 4 named "crash", attached
2 - skip turn
3 - game will crash

[1oom_save4.zip](https://github.com/KilgoreTroutMaskReplicant/1oom/files/1972544/1oom_save4.zip)

**Comment by KilgoreTroutMaskReplicant** [comment]
Just a note: I hope you are not manually saving after each turn. "Next Turn" automatically saves to slot 8 and F10 to slot 7. In case you are copying these back to other slots to retest then thank you for the extra effort!
