### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#8]
Game crashes after end of turn

Running latest version of source compiled today.

How to replicate:
1 - Load save 1 "new crash"
2 - Game will crash after skipping the beginning new turn messages

[new crash.zip](https://github.com/KilgoreTroutMaskReplicant/1oom/files/1976046/new.crash.zip)

**Comment by KilgoreTroutMaskReplicant** [comment]
Thanks for these. A small request for the next ones: Please do a "git log -1" and copy/paste the "commit 0128376bac..." line as "today" is rather vague and my workflow is a bit asynchronous.
